openapi: 3.1.0
info:
  title: GitHub Start9 API
  version: 1.0.0
  description: Retrieve open issues and tags from Start9 GitHub repos.
servers:
  - url: https://api.github.com
paths:
  /repos/{owner}/{repo}/issues:
    get:
      summary: Get issues from a repo
      operationId: getRepoIssues
      parameters:
        - name: owner
          in: path
          required: true
          schema: { type: string }
        - name: repo
          in: path
          required: true
          schema: { type: string }
        - name: state
          in: query
          schema: { type: string, enum: [open, closed, all], default: open }
      responses:
        '200':
          description: OK
  /repos/{owner}/{repo}/tags:
    get:
      summary: Get tags from a repo
      operationId: getRepoTags
      parameters:
        - name: owner
          in: path
          required: true
          schema: { type: string }
        - name: repo
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
