openapi: 3.1.0
info:
  title: Notion API GPT Action Tools for B1ackSwan_API_GPT
  description: Endpoint to create pages/subpages and append children blocks in Notion. The primary home page is fixed as "B1ackSwan_API_GPT".
  version: 1.0.3
servers:
  - url: https://api.notion.com/v1
    description: Notion API Base URL
paths:
  /pages:
    post:
      operationId: createPageNotion
      summary: Create a new page in the home page "B1ackSwan_API_GPT"
      description: Create a new page under the specified parent. Use this endpoint if you need direct page creation.
      parameters:
        - name: Notion-Version
          in: header
          required: true
          schema:
            type: string
          example: 2022-06-28
          enum:
            - 2022-06-28
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parent:
                  type: object
                  required:
                    - type
                    - page_id
                  properties:
                    type:
                      type: string
                      enum:
                        - page_id
                      description: Always "page_id".
                    page_id:
                      type: string
                      description: ID of the parent page.
                      enum:
                        - B1ackSwan_API_GPT
                properties:
                  type: object
                  description: Properties of the new page, including its title.
                  properties:
                    title:
                      type: array
                      description: The title of the new page.
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                            enum:
                              - text
                            description: Must be "text".
                          text:
                            type: object
                            properties:
                              content:
                                type: string
                                description: Text content of the title.
              required:
                - parent
                - properties
  /blocks/B1ackSwan_API_GPT/children:
    patch:
      operationId: appendBlockNotionGPTPage
      summary: Append children blocks to the home page "B1ackSwan_API_GPT"
      description: Appends children blocks to the hard-coded parent block with ID "B1ackSwan_API_GPT".
      parameters:
        - name: Notion-Version
          in: header
          required: true
          description: Notion API version.
          schema:
            type: string
            example: 2022-06-28
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                children:
                  type: array
                  description: Array of child blocks to append.
                  items:
                    type: object
                    properties:
                      object:
                        type: string
                        example: block
                      type:
                        type: string
                        example: heading_2
                      heading_2:
                        type: object
                        properties:
                          rich_text:
                            type: array
                            items:
                              type: object
                              properties:
                                type:
                                  type: string
                                  example: text
                                text:
                                  type: object
                                  properties:
                                    content:
                                      type: string
                                      example: Lacinato kale
                                    link:
                                      type: object
                                      nullable: true
                                      properties:
                                        url:
                                          type: string
                                          example: https://example.com
      responses:
        "200":
          description: A paginated list of the created children blocks.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
        "400":
          description: Bad request.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
        "404":
          description: Not Found.
        "429":
          description: Rate limit exceeded.
      security:
        - bearerAuth: []
      headers:
        Authorization:
          required: true
          schema:
            type: string
            example: Bearer your_notion_api_key
        Content-Type:
          required: true
          schema:
            type: string
            example: application/json
        Notion-Version:
          required: true
          schema:
            type: string
            example: 2022-06-28
  /blocks/{block_id}/children:
    patch:
      operationId: appendBlock
      summary: Add a block with content
      parameters:
        - name: Notion-Version
          in: header
          required: true
          schema:
            type: string
          example: 2022-06-28
          enum:
            - 2022-06-28
        - name: block_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                children:
                  type: array
                  description: Array of child blocks to append.
                  items:
                    type: object
                    properties:
                      object:
                        type: string
                        example: block
                      type:
                        type: string
                        example: heading_2
                      heading_2:
                        type: object
                        properties:
                          rich_text:
                            type: array
                            items:
                              type: object
                              properties:
                                type:
                                  type: string
                                  example: text
                                text:
                                  type: object
                                  properties:
                                    content:
                                      type: string
                                      example: Lacinato kale
                                    link:
                                      type: object
                                      nullable: true
                                      properties:
                                        url:
                                          type: string
                                          example: https://example.com
      responses:
        "200":
          description: A paginated list of newly created children blocks.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
        "400":
          description: Bad request.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
        "404":
          description: Not Found.
        "429":
          description: Rate limit exceeded.
      security:
        - bearerAuth: []
      headers:
        Authorization:
          required: true
          schema:
            type: string
            example: Bearer your_notion_api_key
        Content-Type:
          required: true
          schema:
            type: string
            example: application/json
        Notion-Version:
          required: true
          schema:
            type: string
            example: 2022-06-28
    get:
      operationId: retrieveBlock
      summary: Retrieve block children
      parameters:
        - name: block_id
          in: path
          required: true
          schema:
            type: string
        - name: Notion-Version
          in: header
          required: true
          schema:
            type: string
          example: 2022-06-28
          enum:
            - 2022-06-28
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        has_children:
                          type: boolean
  /search:
    post:
      operationId: search
      summary: Search
      parameters:
        - name: Notion-Version
          in: header
          required: true
          schema:
            type: string
          example: 2022-06-28
          enum:
            - 2022-06-28
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                filter:
                  type: object
                  properties:
                    value:
                      type: string
                    property:
                      type: string
                sort:
                  type: object
                  properties:
                    direction:
                      type: string
                    timestamp:
                      type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: array
                          items:
                            type: object
                            properties:
                              type:
                                type: string
                              text:
                                type: object
                                properties:
                                  content:
                                    type: string
  /subpages:
    post:
      operationId: createSubpage
      summary: Create a new subpage under the Primary Home Page
      description: >
        Creates a plain subpage under the home page "B1ackSwan_API_GPT". Payload must include a "title" and may include optional "children" blocks. The "title" is converted to a heading block; parent is fixed.
      parameters:
        - name: Notion-Version
          in: header
          required: true
          schema:
            type: string
          example: 2022-06-28
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: The title for the new subpage.
                children:
                  type: array
                  description: Optional additional content blocks.
                  items:
                    type: object
      responses:
        '200':
          description: Subpage created successfully under the primary home page.
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas: {}
